Add Skinny animation sample.
tgc-utn/tgc-monogame-samples pull request #79
Opened 2023-05-29 02:17 UTC by rejurime

* Add skinny animation sample.
* Add CustomPipelineManager to process animations content.

2023-06-14 00:27 UTC, Javier-Rotelli commented on TGC.MonoGame.Samples/Animations/PipelineExtension/CustomPipelineManager.cs
> +        var projectDirectory = PathHelper.Normalize(Directory.GetCurrentDirectory());
```suggestion
        var projectDirectory = PathHelper.Normalize(System.IO.Path.GetDirectoryName(Assembly.GetEntryAssembly().Location));
```

2023-06-27 01:11 UTC, AVinitzca requested changes
Se ve lindo pero hay que cambiar un par de cosas.

2023-06-27 01:11 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/BoneInfo.cs
> +    public Keyframe Keyframe1 { get; set; }
Evitaría números en las propiedades, `KeyFrameOne` o `KeyFrameFrom` y `KeyFrameTo` quedaría mejor.

2023-06-27 01:11 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/PipelineExtension/CustomPipelineManager.cs
> +            { "ColorKeyColor", "0,0,0,0" },
Por qué están estas líneas acá?

2023-10-03 23:19 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/PipelineExtension/CustomPipelineManager.cs
> +        var projectDirectory = PathHelper.Normalize(Directory.GetCurrentDirectory());
Voy a ir por esta opcion `var projectDirectory = PathHelper.Normalize(AppDomain.CurrentDomain.BaseDirectory);` me parecio mas limpia. Lo probe tanto desde el ide como desde la terminal, que fue lo que la vez pasada no probe 😝

2023-10-03 23:57 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +        if (Model == null)
Pero si haces un new y le das Draw model es null. No deberia pasar si quien instancia despues hace un LoadContent, si queres lo saco si hace ruido no pasa nada.

2023-10-04 00:54 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +        if (Model == null)
Poné una excepción

2023-10-04 00:55 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +        if (Model == null)
O sacalo y que rompa.

2023-10-04 01:39 UTC, rejurime commented on docs/install/install-windows.md
> +
No hay chance ya esta aca 😗

2023-10-04 01:39 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/PipelineExtension/CustomPipelineManager.cs
> +        var projectDirectory = PathHelper.Normalize(Directory.GetCurrentDirectory());
Fui por otro enfoque pero ya tengo en cuenta donde esta el ensamblado, aunque todo esto necesita un refactor para no tener tanta logica de manejo de carpetas, pero eso ira en otra iteracion.

2023-10-04 02:35 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +        Debug.Assert(ModelExtra != null);
De hecho no veo como podría ser extra ya que se carga en `AnimationProcessor.Process` y se inicializa a nivel estático, con lo cual minimo va a tener un objeto sin estado interno pero creado.

2023-10-04 02:35 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +        Debug.Assert(ModelExtra != null);
Asi que se va.

2023-10-04 02:44 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +                        basicEffect.EnableDefaultLighting();
Esta parte del Effect, mejor si la dejo afuera del draw? me refiero poner esta logica x fuera en el sample del efecto lo que aplico al Effect, mas que nada xq si saco el switch y dejo solo la parte de Skinny esto sera siempre asi... no estoy dando la chance de sobrescribir la logica. Por eso lo decias? o capaz me estoy enredando jeje

2023-10-04 03:03 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/AnimationPlayer.cs
> +    private float _position;
Unifique los privados a que sean todos _ creo que antes de ver si los publicos realmente deben ser publicos podriamos dejarlo para un refactor despues.

2023-10-04 03:09 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/BoneInfo.cs
> +    public BoneInfo(DataTypes.Bone bone)
Y si no quiero? que onda? 👿

2023-10-04 03:10 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/BoneInfo.cs
> +    public BoneInfo(DataTypes.Bone bone)
Es más jodido de leer así

2023-10-04 03:13 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/DataTypes/AnimationClip.cs
> +namespace TGC.MonoGame.Samples.Animations.DataTypes;
Me gustaria un nombre que englobe estas clases ya que son similares pero distintas a las demas, sueltas en animations no me das una vista rapida de que voy a encontrar en las mismas.

2023-10-04 03:21 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/PipelineExtension/CustomPipelineManager.cs
> +            { "ColorKeyColor", "0,0,0,0" },
El Pipeline necesita esos parametros. La idea es hacer un refactor de eso y sacar afuera a archivos auxiliares, el tema es que hay que emular algunas cosas que genera el content builder en principio.

2023-10-04 03:23 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/Bone.cs
> +        // I am not supporting scaling in animation in this example, so I extract the bind scaling from the bind transform and save it.
Por? si queres lo puedo redactar de otra forma no tan personal.

2023-10-04 04:29 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/Bone.cs
> +        // I am not supporting scaling in animation in this example, so I extract the bind scaling from the bind transform and save it.
Ok, eso está bien

2023-10-05 01:30 UTC, rejurime commented on TGC.MonoGame.Samples/Animations/Models/BoneInfo.cs
> +    public BoneInfo(DataTypes.Bone bone)
No se, no se, eso de las ordenes conmigo no va 👿

2023-10-17 00:41 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +                        basicEffect.EnableDefaultLighting();
Lo decía porque un Model en teoría no debería tener ambas BasicEffect y SkinnedEffect. En un futuro cualquiera puede pisar esto por su efecto custom y es la idea.

2023-10-17 00:41 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +                        basicEffect.EnableDefaultLighting();
Es decir, al igual que el Model, nadie va a usar este método Draw directamente si quiere implementar un shader custom. Está bien sacarlo y asumir que si entra por acá todos los Effect dentro del Model son Skinned.

2023-10-17 00:44 UTC, AVinitzca commented on TGC.MonoGame.Samples/Animations/Models/AnimatedModel.cs
> +    public List<AnimationClip> Clips => _modelExtra.Clips;
No pongas propiedades entre constructores y funciones. Es más legible si es variables privadas, después propiedades, después constructores y destructores, después métodos, después métodos estáticos.

2023-11-18 15:29 UTC, merged